### ISSUE TITLE
How do I use it?

### ISSUE THREAD

**Issue by markusa380** [ensime/ensime-lsp-clients#1]
This project seems interesting, but I am unable to figure out how to install it.
Editor: atom

**Comment by laughedelic** [comment]
Hi @MarkusA380, I'm not a maintainer, but I'll try to answer. AFAIK this is not published anywhere yet, so you will have to build it from sources and install manually. Here are approximate instructions (not tested):

0. instal Atom IDE package first: `apm install atom-ide-ui language-scala`
1. clone this repo
2. open sbt in it and run `generateAtomPlugin`
3. now go to the plugin: `cd ensime-lsp-atom` and run

    ```
    apm link --dev
    apm install
    ```
    This should install this as a dev-package.

4. go to some Ensime-ready project and open Atom in dev-mode: `atom -d .`
5. something should happen, the plugin will try to launch Ensime server and connect to it

I will try it out myself later and correct it if needed. I hope this helps.

**Comment by markusa380** [comment]
After following the steps provided atom will show:
```
IDE-Scala language server stopped unexpectedly.
at org.ensime.config.richconfig.package$.parseServerConfig(richconfig.scala:24)
at org.ensime.server.Server$.loadConfig(Server.scala:135)
at org.ensime.server.Server$.main(Server.scala:146)
at org.ensime.server.Server.main(Server.scala)
```
I wouldn't know where to find a log file in Atom.

**Comment by vovapolu** [comment]
@MarkusA380 what ensime version do you use? LSP works only for 3.0.0-SNAPSHOT

**Comment by markusa380** [comment]
The steps @laughedelic has described resulted in the installation of ensime-lsp-atom, language-scala for atom and of course the `addSbtPlugin("org.ensime" % "sbt-ensime" % "2.1.0")`
What are you referring to, @vovapolu?

**Comment by vovapolu** [comment]
Try to use `3.0.0-SNAPSHOT` version of ensime http://ensime.github.io/build_tools/sbt/#unstable-server

**Comment by markusa380** [comment]
According to the guide of @vovapolu , in my .sbt/1.0/ folder I created:

- plugins/plugins.sbt with the `addSbtPlugin` command
- global.sbt with the snippet provided

When starting Atom, there is no more Error, I can also now open the configuration for the ensime-scala plugin and change things like the Java Path and some small configuration. (This was impossible before, probably because of the crash)

But I am unable to find `ENSIME: Start` in the command menu and I do not see any linting or code completion.

**Comment by vovapolu** [comment]
@laughedelic Solution with `--dev` option doesn't work. Regular `apm link` and `atom` work as expected.

**Comment by vovapolu** [comment]
The plugin seems to work, but the server has some troubles right now...

**Comment by laughedelic** [comment]
> Solution with --dev option doesn't work. Regular apm link and atom work as expected.

OK. It's not important.

> The plugin seems to work, but the server has some troubles right now...

@vovapolu could you provide any details? Is it anything critical or something easy to fix?

**Comment by n3ziniuka5** [comment]
I am trying to get this working with vscode, but there are no instructions. I ran `sbt generateVscodePlugin` and it did something, but I am not sure how to proceed further.

Vscode extensions are packaged in a `.vsix` file, but no `.vsix` file was generated.

**Comment by rorygraves** [comment]
@n3ziniuka5 The vscode plugin is available from the VS code marketplace
Search for 'Scala' - you do not need to build it manually.

**Comment by markusa380** [comment]
@rorygraves The plugin on the vscode marketplace was tested on two machines with two installations of vscode, both times not working at all.

**Comment by rorygraves** [comment]
@MarkusA380 I'm looking at it currently.

**Comment by laughedelic** [comment]
Neither VSCode, nor Atom plugins in this repo are **not published** in the stores. You have to build it locally. Rough instructions for VSCode would look like this (~~not tested~~):

First, install extension deps:
```
cd ensime-lsp-vscode
npm install
```

Then you can just open this extension in VSCode (`code .`) and run it in debug mode: `Debug` > `Start debugging` or <kbd>F5</kbd>. A new window will open, choose some Scala project where you have an `.ensime` config and open a Scala file. In the first window (of the extension) you can see the logs in the Debug Console. If you see these errors:
> Received message which is neither a response nor a notification message

Congratulations! The client extension works, but it won't work anyway, because the server is broken at the moment: https://github.com/ensime/ensime-server/issues/1911.

----

Alternatively, you can build the vsix and install it (but it's not very convenient for development, because you will need to rebuild it every time):

```
vsce package # run `npm install -g vsce` first, if you don't have it
code --install-extension scala-lsp-0.1.0.vsix  # fix the name/version
```

I tried it and something failed, probably I'm doing it in a wrong way.

----

**UPD**: tested and updated with more details.

**Comment by n3ziniuka5** [comment]
https://github.com/ensime/ensime-server/issues/1911 is merged now, though I am not sure if the updated version has been published yet. Anyway, I am trying to run the vscode plugin and now I am getting this upon server startup:
```
Exception in thread "main" com.typesafe.config.ConfigException$Missing: No configuration setting found for key 'ensime.config'
	at com.typesafe.config.impl.SimpleConfig.findKeyOrNull(SimpleConfig.java:156)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:174)
	at com.typesafe.config.impl.SimpleConfig.findOrNull(SimpleConfig.java:180)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
	at org.ensime.config.richconfig.package$.parseServerConfig(richconfig.scala:24)
	at org.ensime.server.Server$.loadConfig(Server.scala:155)
	at org.ensime.server.Server$.main(Server.scala:170)
	at org.ensime.server.Server.main(Server.scala)
```

Using version `2.6.0` of `sbt-ensime`. Am I supposed to create `.ensime-server.conf` somewhere?
